const String AppTitle = 'app_title',
    RegisterTitle = 'register_title',
    CreateBookTitle = 'create_book_title',
    EditBookTitle = 'edit_book_title',
    BookTitle = 'book_title',
    BookAuthor = 'book_author',
    BookPublisher = 'book_publisher',
    BookPrice = 'book_price',
    BookPages = 'book_pages',
    TitleRequired = 'title_required',
    AuthorRequired = 'author_required',
    PriceRequired = 'price_required',
    PagesRequired = 'pages_required',
    Delete = 'delete',
    PublishedBy = 'published_by',
    BooksDrawerItem = 'books_drawer_item',
    AddBooks = 'add_books',
    Pages = 'pages',
    Settings = 'settings',
    Statistics = 'statistics',
    Import = 'import',
    Export = 'export',
    ExportSuccess = 'export_success',
    EditProgress = 'edit_progress',
    PagesPerDay = 'pages_per_day',
    Days = 'days',
    FetchBooksFailed = 'fetch_books_failed',
    NoResults = 'no_results',
    Search = 'search',
    GeneralData = 'general_data',
    TotalPages = 'total_pages';

final de = {
  AppTitle: 'TrackIt',
  RegisterTitle: 'Registrieren',
  CreateBookTitle: 'Buch erstellen',
  EditBookTitle: 'Buch ändern',
  BookTitle: 'Titel',
  BookAuthor: 'Autor',
  BookPublisher: 'Herausgeber',
  BookPrice: 'Preis',
  BookPages: 'Anzahl Seiten',
  TitleRequired: 'Titel ist ein Pflichtfeld',
  AuthorRequired: 'Autor ist ein Pflichtfeld',
  PriceRequired: 'Preis ist ein Pflichtfeld',
  PagesRequired: 'Seitenanzahl ist ein Pflichtfeld',
  PublishedBy: 'Herausgegeben von ',
  Delete: 'Löschen',
  BooksDrawerItem: 'Alle Bücher',
  AddBooks: 'Füge deine Bücher hinzu',
  Pages: 'Seiten',
  Settings: 'Einstellungen',
  Statistics: 'Statistiken',
  Import: 'Daten importieren',
  Export: 'Daten exportieren',
  ExportSuccess: 'Daten wurden exportiert',
  EditProgress: 'Fortschritt anpassen',
  PagesPerDay: 'Seiten pro tag',
  Days: 'Tage',
  FetchBooksFailed: 'Fehler bei der Websuche',
  NoResults: 'Keine Ergebnisse',
  Search: 'Suche',
  GeneralData: 'Allgemeine Daten',
  TotalPages: 'Seiten gesamt: '
};

final en = {
  AppTitle: 'TrackIt',
  RegisterTitle: 'Sign up',
  CreateBookTitle: 'Create book',
  EditBookTitle: 'Edit book',
  BookTitle: 'Title',
  BookAuthor: 'Author',
  BookPublisher: 'Publisher',
  BookPrice: 'Price',
  BookPages: 'Number pages',
  TitleRequired: 'Title is required',
  AuthorRequired: 'Author is required',
  PriceRequired: 'Price is required',
  PagesRequired: 'Number of pages is required',
  PublishedBy: 'Published by ',
  Delete: 'Delete',
  BooksDrawerItem: 'All books',
  AddBooks: 'Add your books',
  Pages: 'pages',
  Settings: 'Settings',
  Statistics: 'Statistics',
  Import: 'Import data',
  Export: 'Export data',
  ExportSuccess: 'Data exported successfully',
  EditProgress: 'Edit progress',
  PagesPerDay: 'Pages per day',
  Days: 'days',
  FetchBooksFailed: 'Error while fetching data',
  NoResults: 'No Results',
  Search: 'Search',
  GeneralData: 'General data',
  TotalPages: 'Total pages: '
};
