const String AppTitle = 'app_title',
    RegisterTitle = 'register_title',
    CreateBookTitle = 'create_book_title',
    EditBookTitle = 'edit_book_title',
    BookTitle = 'book_title',
    BookAuthor = 'book_author',
    BookPublisher = 'book_publisher',
    BookPrice = 'book_price',
    BookPages = 'book_pages',
    TitleRequired = 'title_required',
    AuthorRequired = 'author_required',
    PriceRequired = 'price_required',
    PagesRequired = 'pages_required',
    Delete = 'delete',
    PublishedBy = 'published_by',
    BooksDrawerItem = 'books_drawer_item',
    AddBooks = 'add_books',
    Pages = 'pages',
    Settings = 'settings',
    Statistics = 'statistics',
    Import = 'import',
    Export = 'export',
    ExportSuccess = 'export_success',
    EditProgress = 'edit_progress',
    PagesPerDay = 'pages_per_day',
    Days = 'days',
    FetchBooksFailed = 'fetch_books_failed',
    NoResults = 'no_results',
    Search = 'search',
    TotalPages = 'total_pages',
    TotalPrice = 'total_price',
    AveragePages = 'average_pages',
    All = 'all',
    CurrentlyReading = 'currently_reading',
    ThisYear = 'this_year',
    Finished = 'finished',
    Gallery = 'gallery',
    TakeImage = 'take_image',
    RemoveImage = 'remove_image',
    Podcasts = 'podcasts',
    AddPodcast = 'add_podcast',
    Episodes = 'episodes',
    Details = 'details',
    StartPage = 'start_page',
    AmountBooks = 'amount_books',
    LastUpdate = 'last_update',
    Minutes = 'minutes',
    Hours = 'hours',
    AmountEpisodes = 'amount_episodes',
    AmountPodcasts = 'amount_podcasts',
    AverageTime = 'average_time',
    TotalTime = 'total_time',
    PodcastAdded = 'podcast_added';

final de = {
  AppTitle: 'TrackIt',
  RegisterTitle: 'Registrieren',
  CreateBookTitle: 'Buch erstellen',
  EditBookTitle: 'Buch ändern',
  BookTitle: 'Titel',
  BookAuthor: 'Autor',
  BookPublisher: 'Herausgeber',
  BookPrice: 'Preis',
  BookPages: 'Anzahl Seiten',
  TitleRequired: 'Titel ist ein Pflichtfeld',
  AuthorRequired: 'Autor ist ein Pflichtfeld',
  PriceRequired: 'Preis ist ein Pflichtfeld',
  PagesRequired: 'Seitenanzahl ist ein Pflichtfeld',
  PublishedBy: 'Herausgegeben von ',
  Delete: 'Löschen',
  BooksDrawerItem: 'Bücher',
  AddBooks: 'Füge deine Bücher hinzu',
  Pages: 'Seiten',
  Settings: 'Einstellungen',
  Statistics: 'Statistiken',
  Import: 'Daten importieren',
  Export: 'Daten exportieren',
  ExportSuccess: 'Daten wurden exportiert',
  EditProgress: 'Fortschritt anpassen',
  PagesPerDay: 'Historie',
  Days: 'Tage',
  FetchBooksFailed: 'Fehler bei der Websuche',
  NoResults: 'Keine Ergebnisse',
  Search: 'Suche',
  TotalPages: 'Seiten gesamt:',
  TotalPrice: 'Gesamtpreis',
  AveragePages: 'Tagesdurchschnitt',
  All: 'Alle',
  CurrentlyReading: 'Am Lesen',
  Finished: 'Beendet',
  ThisYear: 'Dieses Jahr',
  Gallery: 'Gallerie',
  TakeImage: 'Foto aufnehmen',
  RemoveImage: 'Bild entfernen',
  Podcasts: 'Podcasts',
  AddPodcast: 'Podcast hinzufügen',
  Episodes: 'Episoden',
  Details: 'Detail',
  StartPage: 'Startseite',
  AmountBooks: 'Gelesene Bücher',
  LastUpdate: 'Letztes Update: ',
  Minutes: 'Minuten',
  Hours: 'Stunden',
  AmountEpisodes: 'Gehörte Episoden',
  AmountPodcasts: 'Gehörte Podcasts',
  TotalTime: 'Gesamtzeit',
  AverageTime: 'Tagesdurchschnitt',
  PodcastAdded: 'Podcast hinzugefügt',
};

final en = {
  AppTitle: 'TrackIt',
  RegisterTitle: 'Sign up',
  CreateBookTitle: 'Create book',
  EditBookTitle: 'Edit book',
  BookTitle: 'Title',
  BookAuthor: 'Author',
  BookPublisher: 'Publisher',
  BookPrice: 'Price',
  BookPages: 'Number pages',
  TitleRequired: 'Title is required',
  AuthorRequired: 'Author is required',
  PriceRequired: 'Price is required',
  PagesRequired: 'Number of pages is required',
  PublishedBy: 'Published by ',
  Delete: 'Delete',
  BooksDrawerItem: 'Books',
  AddBooks: 'Add your books',
  Pages: 'pages',
  Settings: 'Settings',
  Statistics: 'Statistics',
  Import: 'Import data',
  Export: 'Export data',
  ExportSuccess: 'Data exported successfully',
  EditProgress: 'Edit progress',
  PagesPerDay: 'History',
  Days: 'days',
  FetchBooksFailed: 'Error while fetching data',
  NoResults: 'No Results',
  Search: 'Search',
  TotalPages: 'Total pages',
  TotalPrice: 'Total price',
  AveragePages: 'Average pages per day',
  All: 'All',
  CurrentlyReading: 'Currently reading',
  Finished: 'Finished',
  ThisYear: 'This year',
  Gallery: 'Gallery',
  TakeImage: 'Take image',
  RemoveImage: 'Remove image',
  Podcasts: 'Podcasts',
  AddPodcast: 'Add Podcast',
  Episodes: 'Episodes',
  Details: 'Detail',
  StartPage: 'Initial page',
  AmountBooks: 'Read books',
  LastUpdate: 'Last update: ',
  Minutes: 'minutes',
  Hours: 'hours',
  AmountEpisodes: 'Listened episodes',
  AmountPodcasts: 'Listened podcasts',
  AverageTime: 'Average time',
  TotalTime: 'Total time',
  PodcastAdded: 'Podcast added',
};

